apiVersion: batch/v1
kind: Job

metadata:
  name: playwright-job
  namespace: automation

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: playwright

          image: playwright-runner-kuber:latest

          imagePullPolicy: Never

          workingDir: /app

          command:
            - sh
            - -c
            - |
                browserArgs=$(echo "$BROWSERS" | tr ',' '\n' | sed 's/^/--project=/' | tr '\n' ' ')

                grepPattern=$(echo "$SUITES" | tr ',' '\n' | sed 's/^/@/' | paste -sd'|' -)

                echo "Running:"
                echo "npx playwright test $browserArgs --grep \"$grepPattern\""

                npx playwright test $browserArgs --grep "$grepPattern"

          env:
            - name: ENV
              value: "${ENV}"

            - name: BROWSERS
              value: "${BROWSER}"

            - name: SUITES
              value: "${SUITE}"