apiVersion: batch/v1
kind: Job

metadata:
  name: playwright-${BROWSER}-${BUILD_NUMBER}
  namespace: automation

spec:
  backoffLimit: 0

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: playwright

          # image: playwright-runner-kuber:latest
          image: playwright-java:1.0

          imagePullPolicy: Never

          workingDir: /app

          command:
            - sh
            - -c
            - |
                browserArgs=$(echo "$BROWSERS" | tr ',' '\n' | sed 's/^/--project=/' | tr '\n' ' ')

                grepPattern=$(echo "$SUITES" | tr ',' '\n' | sed 's/^/@/' | paste -sd'|' -)

                echo "Running:"
                echo "npx playwright test $browserArgs --grep \"$grepPattern\""

                git clone https://github.com/rajatrc2042-lab/playwright-jenkins-docker.git
                cd playwright-jenkins-docker
                npm ci
                npx playwright test $browserArgs --grep "$grepPattern"

          env:
            - name: ENV
              value: "${ENV}"

            - name: BROWSERS
              value: "${BROWSER}"

            - name: SUITES
              value: "${SUITE}"